### ISSUE TITLE
feat: deploy mock contracts

### ISSUE THREAD

**Issue by 0xneves** [blockful-io/swaplace-contracts#100]
We need a script to deploy and mint ERC20 and ERC721 to be used as mocks for the Testnets and Local Nets

Proposal of scripts:
- Deploy the mocks contracts
- Mint of tokens
- Approvals of tokens #99

**Comment by 0xneves** [comment]
Moved to interation 5 due to delay because of ChainLink Hackathon

**Comment by blackbeard002** [comment]
Hey @0xneves can I take this up?

**Comment by blackbeard002** [comment]
Made a PR. Ready for review. #108 []()

**Comment by 0xneves** [comment]
Solved in #108
