### ISSUE TITLE
docs: generate docs using solidity-docgen and natspec

### ISSUE THREAD

**Issue by 0xneves** [blockful-io/swaplace-contracts#105]
Turn the Swaplace Natspec format into documentation format as described by the following links:
https://github.com/OpenZeppelin/solidity-docgen
https://github.com/HQ20/soldoc

I liked the `solidity-docgen` more personally

**Comment by dipanshuhappy** [comment]
Sup @0xneves, would like to work on this task , I have some experience documenting solidity for [viaprize](github.com/viaprize/viaprize)

**Comment by 0xneves** [comment]
closed by #109
