### ISSUE TITLE
refactor: gas optimization in Swaplace.sol

### ISSUE THREAD

**Issue by blackbeard002** [blockful-io/swaplace-contracts#106]
Hey @0xneves,  
In the function createSwap() the state variable 'swapId' is used thrice (excluding swapId++) making it 3 sloads. Instead storing 'swapId' to a local variable brings it down to 1 sload and using the local variable thrice reduces the gas cost. 

And also incrementing the swapId in assembly saves gas.

**Comment by 0xneves** [comment]
This is an amazing entry @blackbeard002 !!

I'm moving to review so I can further check on the gas optimization and legibility

**Comment by 0xneves** [comment]
Closed by #107
