### ISSUE TITLE
feat: adding a receiver as parameter in the accept swap function

### ISSUE THREAD

**Issue by 0xneves** [blockful-io/swaplace-contracts#119]
There is no reason why not allowing to choose the receiver when calling acceptSwap, which is currently setting msg.sender as the receiver of the assets.

Proposal:
- add an address type into the acceptSwap parameter with the name of receiver.
- instead of sending the assets to the msg.sender, send it to the receiver instead.

**Comment by blackbeard002** [comment]
Hey @0xneves I wanna work on this

**Comment by 0xneves** [comment]
Hey @blackbeard002 

I was waiting your PR 🙈

**Comment by 0xneves** [comment]
This task is not hard, come'on guys

**Comment by 0xjoaovpsantos** [comment]
@0xneves @blackbeard002 

HEY HEY GUYS 

I saw that this issue is stopped a while and I did it guys :) 

PR with all documentation about: https://github.com/blockful-io/swaplace-contracts/pull/149
