### ISSUE TITLE
feat: set default providers for EVM networks

### ISSUE THREAD

**Issue by 0xneves** [blockful-io/swaplace-contracts#12]
This task consists of finding default providers specified by the mainnet itself for the following EVM networks:

-BNB
-MATIC
-ETH
-AVAX
-FTM
-ASTR

They should be set in '.env.sample' file that the task assignee should create as well.
They should be implemented in the hardhat config file.

**Comment by Mitish98** [comment]
I can and will do this task

**Comment by Mitish98** [comment]
Hey, I wanna do it
