### ISSUE TITLE
refactor: rename of variable swapId

### ISSUE THREAD

**Issue by 0xneves** [blockful-io/swaplace-contracts#120]
The `swapId` variable is more of a "totalSupply" of trades. Hence a legibility issue.
```
    /// @dev Swap Identifier counter.
    uint256 public swapId;
```

Proposal:
- change the name of the variable into `_totalSwaps`
- create a getter for `_totalSwaps` named "totalSwaps"

We are also taking this opportunity to disable the automatic getter for public functions by changing the "public" modifier in `_totalSwaps` into "private".

We are adding the underscore ("_") to notify its type.

**Comment by RafaDSan** [comment]
I am working on this task!
