### ISSUE TITLE
docs: research gas and cost efficiency for event emission

### ISSUE THREAD

**Issue by 0xneves** [blockful-io/swaplace-contracts#121]
When thinking of making it easier the life of the devs, who implement indexers throughout the event system easier, they might find it useful that we describe the entire trade in the logs... The most important to boost now, is with the addition of the `allowed` field into the event args. This way we can track who created an offer, and to whom.

Now imagine that the following function:
```
 emit SwapCreated(l_swapId, msg.sender, swap.expiry);
```
...carried the `allowed` field, the `bidding` and `asking`, so we could track the swaps without the need to request view calls to fill Indexes for their front-end to display the swap contents.

Proposal:
- Prepare a spreadsheet with the gas usage based on the current and proposed events emitted and set for a comparison.
- Estimate the gas when calling `createSwap` and record their gas usage.
- Take measures of the gas usage.
- Add the `allowed` field in the events. Take Measure.
- Add the `bidding` and `asking` field in the events. Take Measure.
- Add the price of ETH at $2.200 and calculate the gas cost in dollars.

By understanding the unitary extra cost for each user in ETH, we could charge the user to facilitate the implementation side of the protocol, or we could optimize, reducing gas usage and user cost, in exchange for the implementation side dealing with extra layers that could lower user expirience.

**Comment by 0xjoaovpsantos** [comment]
Hey @0xneves , I'll get this issue ok?

**Comment by 0xneves** [comment]
Hey @0xjoaovpsantos
I'm glad you are helping in this task!! Its starting to buzz as the dApp gets shape and our graph is all ready also.

Will help a lot 🙌

**Comment by 0xjoaovpsantos** [comment]
I opened a PR :) 

https://github.com/blockful-io/swaplace-contracts/pull/146
