### ISSUE TITLE
feat: add a default private key using the hardhat first address from the node list

### ISSUE THREAD

**Issue by 0xneves** [blockful-io/swaplace-contracts#13]
Run this:
`npx hardhat node`

A list of private keys will be provided in order from 1 to 10, those are the default hardhat keys.

Take the first 3 keys and place them in the '.env.sample' file, we'll be using:
1st as Deployer
2nd as Trade Creator
3rd as Trade Acceptee

They should be implemented in the hardhat config file

**Comment by Mitish98** [comment]
I can and will do this task

**Comment by Mitish98** [comment]
I can do this task
