### ISSUE TITLE
docs: move TL;DR to the top of the readme

### ISSUE THREAD

**Issue by 0xneves** [blockful-io/swaplace-contracts#137]
Proposal:
- Change the TLDR: into TL;DR
- Add more features, like create swap, accept swap
- Describe the other fields, use example from the Uniswap Permit2

**Comment by 0xjoaovpsantos** [comment]
Can I get this issue? @0xneves

**Comment by 0xneves** [comment]
Let's go! Send us da pull request!

**Comment by 0xjoaovpsantos** [comment]
https://github.com/blockful-io/swaplace-contracts/pull/148

**Comment by 0xneves** [comment]
> #148
Hey @0xjoaovpsantos will give you a hint on github:

You can write the following in your PR:
`closes #<issue>`

it will automatically close the issue when approved and also link the PR with the issue. 

The way you are doing by referring to the PR in the issue won't suit the linking between them.

**Comment by 0xneves** [comment]
closed by #148
