### ISSUE TITLE
feat: create a way to handle errors

### ISSUE THREAD

**Issue by luislucena16** [blockful-io/swaplace-contracts#141]
- considering solidity updates and good semantic practices, it can be: 
```bash
if (owner != msg.sender) revert NotAllowed();
```
- helps to make error messages more verbose and simple to view code for developers or feedback to users.

**Comment by 0xneves** [comment]
Hi @luislucena16 
Referring to the identation, I think its a good idea to shorten characters in the code by removing the "{}" of the if else's, from this:
```
        if (swap.owner != msg.sender) {
            revert InvalidAddress(msg.sender);
        }
```
...to this:
```
        if (swap.owner != msg.sender) revert InvalidAddress(msg.sender);
```

**Comment by luislucena16** [comment]
hey @0xneves 
yes exactly! it allows to handle errors more organized and with better semantics 💫

**Comment by 0xjoaovpsantos** [comment]
Hey guys this issue is available? If so, I would like to get it

@0xneves @luislucena16

**Comment by luislucena16** [comment]
hi @0xjoaovpsantos I'll take care of it!

**Comment by 0xneves** [comment]
Counting on you, this is a fast one, let's go!

**Comment by luislucena16** [comment]
done! PR: https://github.com/blockful-io/swaplace-contracts/pull/157

**Comment by 0xneves** [comment]
Could you speed up this resolution @luislucena16?  Since it is blocking issue #104 from developing. 
Thank you

**Comment by luislucena16** [comment]
done! waiting for your approval
