### ISSUE TITLE
feat: initialize foundry repo for Swaplace-CCIP

### ISSUE THREAD

**Issue by 0xneves** [blockful-io/swaplace-contracts#142]
## Feature Request

Initialize the Foundry repository in this [branch](https://github.com/blockful-io/swaplace-ccip/tree/feat/foundry)

### Describe the Feature Request

- Download Foundry in the repository
- Add OpenZeppelin to the remappings
- Migrate the contracts and scripts into their respective folders

### Describe Preferred Solution

Only setting up the repo and migrating the files is necessary for this issue, among setting OpenZeppelin and RPC configurations.

### Additional Context

I'll create a lot of issues on top of this resolution. CCIP will be a medium<>high difficulty level and will count for this incentives cycle. The sooner this is completed the faster we can release the issues.

**Comment by 0xneves** [comment]
Will move this issue to the ccip-swaplace repo later

**Comment by 0xjoaovpsantos** [comment]
Hey @0xneves , this issue is finished with this repo right? https://github.com/blockful-io/ccip

**Comment by 0xneves** [comment]
Noooo @0xjoaovpsantos , that repo is Solidity and Scripts with Hardhat, we need to instance a new branch to prepare the Foundry setup instead of Hardhat

**Comment by luislucena16** [comment]
hey @0xneves this was the issue I created, it is related to this:
https://github.com/blockful-io/swaplace-contracts/issues/140

**Comment by 0xjoaovpsantos** [comment]
If I can get this issue to work @0xneves :)

**Comment by 0xneves** [comment]
> hey @0xneves this was the issue I created, it is related to this: #140

You proposed foundry for Swaplace, we will not use Foundry for Swaplace.
But for CCIP, as I mentioned in Discord and other issues, it will use Foundry.

**Comment by 0xneves** [comment]
ccip tasks will be more heavy and will extend over February and March

**Comment by luislucena16** [comment]
are the incentives also different?

**Comment by 0xneves** [comment]
Please help me @luislucena16 @0xjoaovpsantos 

There are multiple ways to do this task, as the repo configurations could vary.

I don't want to assign this task to someone due to the diversity of boilerplates that are possible.

Shall we do it like this: 
- [ ] submit your best Foundry Boilerplate and adapt https://github.com/blockful-io/swaplace-ccip into it. I will review how lightweight it is, and the overall usability, among any other features you find interesting. We will debate and implement the best boilerplate for starters. 

I think you can start by submitting a PR for this issue with your best boilerplate for Foundry.

Help us achieve this repository by January 1st week. And I'll start decentralize the ccip contract issues for the community.

**Comment by 0xneves** [comment]
> are the incentives also different?

Not at first sight, it will depend on the grants we acquire in the process. CCIP will charge fees and so as Blockful, since its a monetized product, we will probably have better incentives as the knowledge required to build on top of it will also be higher.

**Comment by 0xneves** [comment]
Is any of you interested in moving on with this task @0xjoaovpsantos and @luislucena16 ?

**Comment by 0xjoaovpsantos** [comment]
Yeah @0xneves !!! In this week i'll upload a proposal :)

**Comment by 0xneves** [comment]
> Yeah @0xneves !!! In this week i'll upload a proposal :)

I'm excited to see what you have been doing! 

The tests are a bonus, you don't have to push it too further, only the repo configuration and compilation are the most sensitive part for this task!

**Comment by 0xneves** [comment]
Let me know if you need anything @0xjoaovpsantos !! I'm actively carving for this issue, as it will kickstart all the next issues for the swaplace-ccip 🤟

**Comment by 0xneves** [comment]
@0xjoaovpsantos It's to remove the hardhat, all-win foundry.

**Comment by 0xneves** [comment]
Hey @0xjoaovpsantos @luislucena16 I've moved this to be a hot task following my last request for change comment in [here](https://github.com/blockful-io/swaplace-ccip/pull/7)

This is past midnight from being ready. I'll be assuming this task myself in case it's not done by this Monday (12).

**Comment by 0xjoaovpsantos** [comment]
Fixed it sir! -> https://github.com/blockful-io/swaplace-ccip/pull/7#issuecomment-1937943722

@0xneves
