### ISSUE TITLE
feat: add docker as infrastructure

### ISSUE THREAD

**Issue by luislucena16** [blockful-io/swaplace-contracts#155]
- dockerise the project with specific versioning in the packages

The goal is to be able to use all `yarn` or `npm` with the same versions and not have problems installing them.

**Comment by luislucena16** [comment]
hey @0xneves please assign this to me, thanks in advance!

**Comment by 0xneves** [comment]
Hey @luislucena16 
I'm having my doubts about the need for docker in this project. The goal described as it would be an issue when handling versions, but my thought is that if a developer is aware of how to use docker, he will be able to manage versioning just fine. 

How do you think Docker could improve the project besides simple versioning?

**Comment by luislucena16** [comment]
@0xneves 

I think about the following:

there are some versions of packages that conflict with each other, but they are specific, some from `ethers` others from `hardhat` etc and it can happen that every time someone wants to test the project and do an `npm i` they install dependencies with different versions even if they are in the same nodejs version. Docker would help to solve that (it can be modified as new versions are released). This way we would avoid unnecessary problems with versions or uploading different dependencies than the ones in `main`, i.e. everyone uses a stable one!

**Comment by 0xneves** [comment]
I don't know if this will be much of an improvement but I'm curious to understand what are you up to! Will assign this to you @luislucena16 , let's go!

**Comment by 0xneves** [comment]
Do we have an update on this @luislucena16 ?

**Comment by 0xneves** [comment]
Hey @luislucena16 I'm bumping this once more since it's been a long time ago. Will close otherwise.

**Comment by 0xneves** [comment]
Closing this issue as it seems not moving forward and it was initially out of scope
