### ISSUE TITLE
chore: create `develop` branch to development

### ISSUE THREAD

**Issue by luislucena16** [blockful-io/swaplace-contracts#156]
- create `develop` branch and assigning it as `default` for changes, is a best practice and helps to protect `main` branch which would only be used for prod.

**Comment by luislucena16** [comment]
hey @0xneves please assign this to me!

**Comment by 0xneves** [comment]
Hey @luislucena16 

We discussed finishing the current incentives round before a release, which would then split into the development branch. Active issues on top of the main branch will soon cease. Let's leave this chore on standby from now. We scheduled this release for January.

**Comment by luislucena16** [comment]
@0xneves 
why not use `develop` for development in general?

**Comment by 0xneves** [comment]
Active issues on top of the main branch will soon cease. 
We discussed finishing the current incentives round before the release of the development branch.
I agree that mature projects should not use the main much. Our project is still a baby, it's not an issue.

**Comment by luislucena16** [comment]
right! understood! :)

**Comment by 0xneves** [comment]
Hey @luislucena16, now it's time to rise from the ashes and submit the develop branch as you proposed.

**Comment by luislucena16** [comment]
okay, I'm going to do it!

**Comment by luislucena16** [comment]
done here: https://github.com/blockful-io/swaplace-contracts/pull/192
I created only a comment to push `develop` branch

**Comment by luislucena16** [comment]
I upload a PR and leave it for you to configure the policies?

**Comment by 0xneves** [comment]
There is no need for policies, just submit a copy of the main branch named develop. We will move forward on the develop but will keep the main as the default.

**Comment by luislucena16** [comment]
yes @0xneves, but remember that I have a fork and I have my develop branch there, I don't have permissions to do it from here

**Comment by 0xneves** [comment]
It's okey, I will create the branch them!

**Comment by 0xneves** [comment]
Issues will be directed to the `develop` branch now.

**Comment by luislucena16** [comment]
@0xneves nice!!
