### ISSUE TITLE
feat: add `prettierrc.json` for solidity

### ISSUE THREAD

**Issue by luislucena16** [blockful-io/swaplace-contracts#160]
- the goal is to add the `prettierrc.json` configuration for solidity and thus establish more order in the files, lines, spaces, etc

@0xneves please assign this to me!

**Comment by 0xneves** [comment]
Closing as it was resolved by #122 and #150

**Comment by luislucena16** [comment]
I suggest reopening this issue and renaming it to `fix`, that prettier file is missing some things
