### ISSUE TITLE
refactor: lower gas cost of createSwap by delegating security checks to the implementer

### ISSUE THREAD

**Issue by 0xneves** [blockful-io/swaplace-contracts#172]
### Describe the Refactor Request

A couple of validations in the createSwap function can be removed to prioritize gas optimization.

### Describe Preferred Solution

By removing the `parseData` from createSwap and leaving only the `swapId` in the event emission we can slightly reduce gas consumption for the final user. Both `if` checks can be done on the front-end while the event should only rely on the `swapId` which should be used by a front-end or back-end to fetch the other information about the swap, which is needed anyways.

### Related Code

```
...
    (address allowed, uint256 expiry) = parseData(swap.config);

    if (expiry < block.timestamp) revert InvalidExpiry(expiry);

    if (swap.biding.length == 0 || swap.asking.length == 0)
      revert InvalidAssetsLength();
...
    emit SwapCreated(swapId, msg.sender, allowed, expiry);
}

```

### Additional Context

This is an optimization vs legibility/usability issue. We decided to prioritize the optimization after checking the issue #104 .

**Comment by blackbeard002** [comment]
Hey @0xneves can I take this? Once you merge #165 I'll get onto this.

**Comment by 0xneves** [comment]
This is probably the last smart-contract-related Swaplace task before a release. I marked the iteration as past week to follow schedule, you must rush this asap @blackbeard002
