### ISSUE TITLE
fix: incorrect event emission on acceptSwap

### ISSUE THREAD

**Issue by 0xneves** [blockful-io/swaplace-contracts#194]
### Current behavior

The event in `acceptSwap` is logging the `allowed` variable from the swap struct, which might be the address 0 in case the swap is open to the public, and the user who accepted will not be present in the log - address(0) will be instead - making it impossible to query the swap using his address when connected to the dApp.

### Expected behavior

We expect that the `acceptSwap` emits the `msg.sender` instead of `allowed` so we can correctly query the user who accepted the swap.

Definition of Done:
- Change `allowed` for `msg.sender`
- Correct the tests that will fail subsequently

### Related code

```
    emit SwapAccepted(swapId, swap.owner, allowed);
```

**Comment by blackbeard002** [comment]
Hey @0xneves I'm on it

**Comment by blackbeard002** [comment]
Hey @0xneves made a PR that closes this #196
