### ISSUE TITLE
epic: native ether and ERC1155 swaps

### ISSUE THREAD

**Issue by 0xneves** [blockful-io/swaplace-contracts#204]
### Describe the Feature Request

The revision branch is out and needs a few tests to guarantee the contract is working correctly. The main subjects that need to be addressed in this epic are:
- Swap with Native Ether
- Swap with ERC1155
- Unitary Tests
- Scripts

Please ping me on GitHub so I can address an issue to you in case you're interested. One at a time, please!
Please ping me on Discord for questions regarding the issues below. Happy coding.

## TARGET BRANCH: [REVISION](https://github.com/blockful-io/swaplace-contracts/tree/revision)

- [x] #205
- [x] #206
- [x] #207
- [x] #208
- [x] #209
- [x] #210
- [x] #211
- [x] #212

### Additional Context

[Check how the native ether transfer works](https://github.com/blockful-io/swaplace-subgraph/issues/32)

**Comment by blackbeard002** [comment]
Hey @0xneves will I be getting assigned for this as well since I closed it all? :eyes: :joy:

**Comment by 0xneves** [comment]
> Hey @0xneves will I be getting assigned for this as well since I closed it all? 👀 😂

This is not an issue, but rather an epic, only means for tracking and managements, thus why I'm assigned

**Comment by blackbeard002** [comment]
> > Hey @0xneves will I be getting assigned for this as well since I closed it all? 👀 😂
> 
> This is not an issue, but rather an epic, only means for tracking and managements, thus why I'm assigned

Yeah yeah I was just kidding 😅
