### ISSUE TITLE
test: create unitary tests to implement native ether transfers in `TestSwaplace.test.ts`

### ISSUE THREAD

**Issue by 0xneves** [blockful-io/swaplace-contracts#206]

**Comment by blackbeard002** [comment]
Hey @0xneves can I take this up? Also could you give me some more info about the issue?

**Comment by 0xneves** [comment]
Yes you may!

> Hey @0xneves can I take this up?

**Comment by blackbeard002** [comment]
Hey @0xneves made a PR that closes this #217
