### ISSUE TITLE
refactor: scripts for running the test suit with makefile need to be upgraded because of native ether feature

### ISSUE THREAD

**Issue by 0xneves** [blockful-io/swaplace-contracts#209]
A lot was changed by #204 PR's. Thus we need to test the Make test called _test-suit-runner_.

Definition of done:
- [ ] Call `make test-suit-runner` after launching `npx hardhat node` to see if the scripts are working correctly.
- [ ] Fix any issue that stops the test suit from running.

Let me know if there are any problems 👍

**Comment by blackbeard002** [comment]
Hey @0xneves  can I take this up??

**Comment by blackbeard002** [comment]
Hey @0xneves ran the `make test-suite-runner` and all the tests ran successfully. 

- [x] Scripts are working as expected.
- [x] No issue that's stopping the test suite from running. 

Test screenshot-1
![one](https://github.com/blockful-io/swaplace-contracts/assets/13573640/1e43e323-502f-4e3f-aa37-c191b6596a6f)

Test screenshot-2
![two](https://github.com/blockful-io/swaplace-contracts/assets/13573640/cf4fc458-41b0-4505-a2e0-df2d3a48690d)

Test screenshot-3
![three](https://github.com/blockful-io/swaplace-contracts/assets/13573640/4e32cb54-72d8-4983-a855-27a1b7e68020)

This closes the current issue #209
