### ISSUE TITLE
feat: create cairo repo to introduce swaplace

### ISSUE THREAD

**Issue by 0xneves** [blockful-io/swaplace-contracts#22]
We are expanding into the Cairo ecosystem of Starknet.

This card proposes to kickstart this development by introducing the repository at first.

Definition of done:
- Running a contract on the localhost
- Running a contract on the devnet

**Comment by web3-engineer** [comment]
assign to me, i'll do it

**Comment by 0xneves** [comment]
Hey @web3-engineer . Sorry for the late response, I apologize for keeping you waiting. 

We've been talking to another developer to aid in this issue among others Cairo related and I forgot to update this issue.
We will do a strong kickstart in the swaplace-cairo-contracts and open for the community to contribute afterward, aiming at January 2nd week. 

Please stay put for more news, I'm closing this issue for now as it was resolved, although time hasn't reached the resolution yet.
