### ISSUE TITLE
docs: refine solidity-docgen into gitbook

### ISSUE THREAD

**Issue by heronlancellot** [blockful-io/swaplace-contracts#228]
### Describe the Feature Request

Definition of done:
- [ ] Refine the Solidity-Docgen with the latest updates from Swaplace.
- [ ] Create an account to implement the gitbook
 

### Related Code
[solidity-docgen](https://github.com/blockful-io/swaplace-contracts/tree/develop/docs/solidity-docgen)

**Comment by 0xneves** [comment]
closed by #233
