### ISSUE TITLE
feat: better README.md for the project's repository

### ISSUE THREAD

**Issue by 0xneves** [blockful-io/swaplace-contracts#24]
I think the bigger question here is:
- What does a good README look like?
- Should it have a short description of the project and long setups?

I've tried to explain a lot in the README but it is still not good enough, maybe needs some fluxes? Or more test commands? I'm getting negative feedback from someone, but is still hard to realize what is it lacking, every readme is different in its way, so I guess it is fine for me as it is. If we look at Uniswap [README](https://github.com/Uniswap/v3-core/tree/main) file, it is very simple and short.

Thus, we are accepting feedback and suggestions on what should be changed! 

This issue will remain open until:
- It is decided by the vast majority that it is viable.

**Comment by RafaDSan** [comment]
This README should be comprehensible for everyone, even for those who are starting on web3, correct? Perhaps a readme that is not necessarily short, but simple, avoiding technical jargon or complex flows (not entirely, but with a simple explanation when used) with a detailed step-by-step guide. Maybe it's a way to approach this README. 

I'd like to contribute to this task! @0xneves

**Comment by 0xneves** [comment]
Thank you for your willingness to help @RafaDSan !! Unfortunately, I'll have to do this task because of the technical character it should introduce for the devs that will use it...

I would love feedback though after I finish it!
