### ISSUE TITLE
refactor: rename Trade keyword from TestTradeFactory.test.ts into Swap

### ISSUE THREAD

**Issue by 0xneves** [blockful-io/swaplace-contracts#37]
Definition of Done:
- Find all the `Trade` keywords and change them into `Swap` as it is more logical following the sex appeal of the project and avoid mismatching with a word that is (for most people) attached to negativity.

**Comment by Mitish98** [comment]
I can and will do this task

**Comment by Mitish98** [comment]
I think i pull request this task with [https://github.com/blockful-io/swaplace-contracts/pull/56](https://github.com/blockful-io/swaplace-contracts/pull/56)
