### ISSUE TITLE
refactor: InvalidExpiryDate custom error into InvalidExpiry only

### ISSUE THREAD

**Issue by 0xneves** [blockful-io/swaplace-contracts#38]
Title describes it well, refactor the name across the repository.

**Comment by Mitish98** [comment]
I can and will do this task

**Comment by 0xneves** [comment]
> I can and will do this task

Sorry @Mitish98 but I was already set as the owner of this task and the resolution was pretty quick, I didn't realize your message. The issue was resolved in #53
