### ISSUE TITLE
docs: swaplace factory should be explained in its interface instead of its contract

### ISSUE THREAD

**Issue by 0xneves** [blockful-io/swaplace-contracts#50]
The descriptions of the SwaplaceFactory.sol do not follow the OpenZeppelin standard.

They should:
- Refer to the interface in the main contract
- Describe its features in the interface contract

This is because when using those features, the explanation is always supposed to be found in the interface to reduce the code size of the main contract and standardize the process of acknowledging what the contract do.

**Comment by Mitish98** [comment]
I can and will do this task
