### ISSUE TITLE
docs: ISwap.sol needs NatSpec comments

### ISSUE THREAD

**Issue by 0xneves** [blockful-io/swaplace-contracts#64]
Follow the same standard used in the rest of the contract (OpenZeppelin's) to describe the interface of ISwap.sol.

Proposal:
- Implement the NatSpec interface for the ISwap.sol

**Comment by Mitish98** [comment]
Hey, 

I can do this issue

**Comment by 0xneves** [comment]
Hey @Mitish98 I saw you haven't finished the task and I'm out of task, so I'll go for it as well
