### ISSUE TITLE
feat: approve scripts to aid swaps

### ISSUE THREAD

**Issue by 0xneves** [blockful-io/swaplace-contracts#99]
Proposal:
- Build `approve` scripts to use with ERC20 and ERC721 
- - must be easy to use and understand
- - must be a script of type export
- - adapted to the current tests where there is approvals

**Comment by Guboehm** [comment]
Hi @0xneves, I'm interested in this task.

**Comment by blackbeard002** [comment]
Hey @Guboehm I'm sorry, I had to make a PR for this issue since it was a part of issue #100 [](url). My PR isn't yet reviewed anyways. Just wanted to give you a heads up.
